"""Node registry with 100+ built-in nodes for ChainForge."""
from dataclasses import dataclass, field
from typing import Any


@dataclass
class NodePort:
    """A port on a workflow node."""
    id: str
    name: str
    type: str = "any"
    required: bool = False


@dataclass
class NodeDefinition:
    """Definition of a workflow node type."""
    type: str
    name: str
    category: str
    description: str
    icon: str = "box"
    color: str = "#6366f1"
    inputs: list = field(default_factory=list)
    outputs: list = field(default_factory=list)
    config_schema: dict = field(default_factory=dict)


# Built-in node definitions (100+ nodes)
NODE_DEFINITIONS: list[NodeDefinition] = [
    # === INPUT NODES (1-10) ===
    NodeDefinition("input_text", "Text Input", "Input", "Plain text input", "text", "#10b981",
                   outputs=[NodePort("out", "Text", "string")],
                   config_schema={"value": {"type": "string", "default": ""}}),
    NodeDefinition("input_number", "Number Input", "Input", "Numeric input", "hash", "#10b981",
                   outputs=[NodePort("out", "Number", "number")],
                   config_schema={"value": {"type": "number", "default": 0}}),
    NodeDefinition("input_boolean", "Boolean Input", "Input", "True/False input", "toggle", "#10b981",
                   outputs=[NodePort("out", "Boolean", "boolean")],
                   config_schema={"value": {"type": "boolean", "default": True}}),
    NodeDefinition("input_json", "JSON Input", "Input", "JSON data input", "code", "#10b981",
                   outputs=[NodePort("out", "JSON", "object")],
                   config_schema={"value": {"type": "string", "default": "{}"}}),
    NodeDefinition("input_file", "File Input", "Input", "File upload input", "file", "#10b981",
                   outputs=[NodePort("out", "File", "object")],
                   config_schema={"accept": {"type": "string", "default": "*/*"}}),
    NodeDefinition("input_date", "Date Input", "Input", "Date picker input", "calendar", "#10b981",
                   outputs=[NodePort("out", "Date", "string")],
                   config_schema={"value": {"type": "string", "default": ""}}),
    NodeDefinition("input_list", "List Input", "Input", "List/array input", "list", "#10b981",
                   outputs=[NodePort("out", "List", "array")],
                   config_schema={"value": {"type": "string", "default": "[]"}}),
    NodeDefinition("input_credentials", "Credentials Input", "Input", "API key or secret", "key", "#10b981",
                   outputs=[NodePort("out", "Credentials", "string")],
                   config_schema={"type": {"type": "string", "default": "api_key"}}),
    NodeDefinition("input_url", "URL Input", "Input", "URL/endpoint input", "link", "#10b981",
                   outputs=[NodePort("out", "URL", "string")],
                   config_schema={"value": {"type": "string", "default": "https://"}}),
    NodeDefinition("input_email", "Email Input", "Input", "Email address input", "mail", "#10b981",
                   outputs=[NodePort("out", "Email", "string")],
                   config_schema={"value": {"type": "string", "default": ""}}),

    # === OUTPUT NODES (11-18) ===
    NodeDefinition("output_text", "Text Output", "Output", "Display text result", "text", "#ef4444",
                   inputs=[NodePort("in", "Text", "string")],
                   config_schema={"format": {"type": "string", "default": "plain"}}),
    NodeDefinition("output_json", "JSON Output", "Output", "Display JSON result", "code", "#ef4444",
                   inputs=[NodePort("in", "JSON", "object")],
                   config_schema={"pretty": {"type": "boolean", "default": True}}),
    NodeDefinition("output_table", "Table Output", "Output", "Display data as table", "table", "#ef4444",
                   inputs=[NodePort("in", "Data", "array")]),
    NodeDefinition("output_chart", "Chart Output", "Output", "Display data as chart", "chart", "#ef4444",
                   inputs=[NodePort("in", "Data", "array")],
                   config_schema={"chart_type": {"type": "string", "default": "bar"}}),
    NodeDefinition("output_file", "File Output", "Output", "Download file result", "download", "#ef4444",
                   inputs=[NodePort("in", "File", "object")]),
    NodeDefinition("output_email", "Email Output", "Output", "Send result via email", "mail", "#ef4444",
                   inputs=[NodePort("in", "Content", "string")],
                   config_schema={"to": {"type": "string", "default": ""}, "subject": {"type": "string", "default": ""}}),
    NodeDefinition("output_webhook", "Webhook Output", "Output", "Send result to webhook", "send", "#ef4444",
                   inputs=[NodePort("in", "Payload", "object")],
                   config_schema={"url": {"type": "string", "default": ""}}),
    NodeDefinition("output_log", "Log Output", "Output", "Log result to console", "terminal", "#ef4444",
                   inputs=[NodePort("in", "Message", "any")],
                   config_schema={"level": {"type": "string", "default": "info"}}),

    # === LLM NODES (19-35) ===
    NodeDefinition("llm_openai", "OpenAI Chat", "LLM", "OpenAI GPT chat completion", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Messages", "array"), NodePort("cfg", "Config", "object", False)],
                   outputs=[NodePort("out", "Response", "string"), NodePort("full", "Full Response", "object")],
                   config_schema={"model": {"type": "string", "default": "gpt-4o-mini"}, "temperature": {"type": "number", "default": 0.7}}),
    NodeDefinition("llm_anthropic", "Anthropic Claude", "LLM", "Anthropic Claude chat", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Messages", "array")],
                   outputs=[NodePort("out", "Response", "string")],
                   config_schema={"model": {"type": "string", "default": "claude-3-haiku-20240307"}}),
    NodeDefinition("llm_ollama", "Ollama Local", "LLM", "Local Ollama model", "cpu", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")],
                   config_schema={"model": {"type": "string", "default": "llama3"}, "endpoint": {"type": "string", "default": "http://localhost:11434"}}),
    NodeDefinition("llm_gemini", "Google Gemini", "LLM", "Google Gemini model", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")],
                   config_schema={"model": {"type": "string", "default": "gemini-1.5-flash"}}),
    NodeDefinition("llm_mistral", "Mistral AI", "LLM", "Mistral AI model", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")],
                   config_schema={"model": {"type": "string", "default": "mistral-small"}}),
    NodeDefinition("llm_cohere", "Cohere", "LLM", "Cohere Command model", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_groq", "Groq", "LLM", "Groq fast inference", "zap", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_together", "Together AI", "LLM", "Together AI models", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_openrouter", "OpenRouter", "LLM", "OpenRouter multi-model", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_azure", "Azure OpenAI", "LLM", "Azure OpenAI Service", "cloud", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_huggingface", "HuggingFace", "LLM", "HuggingFace inference", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_vertex", "Vertex AI", "LLM", "Google Vertex AI", "cloud", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_bedrock", "AWS Bedrock", "LLM", "AWS Bedrock models", "cloud", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_deepseek", "DeepSeek", "LLM", "DeepSeek models", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_qwen", "Qwen", "LLM", "Alibaba Qwen models", "brain", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")]),
    NodeDefinition("llm_custom", "Custom LLM", "LLM", "Custom LLM endpoint", "settings", "#8b5cf6",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Response", "string")],
                   config_schema={"endpoint": {"type": "string"}, "headers": {"type": "object"}}),
    NodeDefinition("llm_embeddings", "Embeddings", "LLM", "Generate text embeddings", "vector", "#8b5cf6",
                   inputs=[NodePort("in", "Text", "string")],
                   outputs=[NodePort("out", "Embeddings", "array")]),

    # === TOOL NODES (36-55) ===
    NodeDefinition("tool_web_search", "Web Search", "Tool", "Search the web", "search", "#f59e0b",
                   inputs=[NodePort("in", "Query", "string")],
                   outputs=[NodePort("out", "Results", "array")],
                   config_schema={"provider": {"type": "string", "default": "serper"}, "num_results": {"type": "number", "default": 5}}),
    NodeDefinition("tool_web_scrape", "Web Scraper", "Tool", "Scrape web page content", "globe", "#f59e0b",
                   inputs=[NodePort("in", "URL", "string")],
                   outputs=[NodePort("out", "Content", "string")]),
    NodeDefinition("tool_calculator", "Calculator", "Tool", "Math calculations", "calculator", "#f59e0b",
                   inputs=[NodePort("in", "Expression", "string")],
                   outputs=[NodePort("out", "Result", "number")]),
    NodeDefinition("tool_code_exec", "Code Executor", "Tool", "Execute Python code", "code", "#f59e0b",
                   inputs=[NodePort("in", "Code", "string")],
                   outputs=[NodePort("out", "Result", "any")],
                   config_schema={"language": {"type": "string", "default": "python"}, "timeout": {"type": "number", "default": 30}}),
    NodeDefinition("tool_shell", "Shell Command", "Tool", "Run shell command", "terminal", "#f59e0b",
                   inputs=[NodePort("in", "Command", "string")],
                   outputs=[NodePort("out", "Output", "string")]),
    NodeDefinition("tool_http", "HTTP Request", "Tool", "Make HTTP requests", "globe", "#f59e0b",
                   inputs=[NodePort("in", "Config", "object")],
                   outputs=[NodePort("out", "Response", "object")],
                   config_schema={"method": {"type": "string", "default": "GET"}, "url": {"type": "string"}, "headers": {"type": "object"}, "body": {"type": "string"}}),
    NodeDefinition("tool_database", "Database Query", "Tool", "Query SQL database", "database", "#f59e0b",
                   inputs=[NodePort("in", "Query", "string")],
                   outputs=[NodePort("out", "Results", "array")],
                   config_schema={"connection": {"type": "string"}, "db_type": {"type": "string", "default": "postgresql"}}),
    NodeDefinition("tool_redis", "Redis", "Tool", "Redis cache operations", "database", "#f59e0b",
                   inputs=[NodePort("in", "Command", "string")],
                   outputs=[NodePort("out", "Result", "any")]),
    NodeDefinition("tool_s3", "S3 Storage", "Tool", "AWS S3 operations", "cloud", "#f59e0b",
                   inputs=[NodePort("in", "Config", "object")],
                   outputs=[NodePort("out", "Result", "object")]),
    NodeDefinition("tool_email", "Send Email", "Tool", "Send email via SMTP", "mail", "#f59e0b",
                   inputs=[NodePort("in", "Content", "object")],
                   outputs=[NodePort("out", "Status", "object")]),
    NodeDefinition("tool_slack", "Slack", "Tool", "Send Slack message", "message", "#f59e0b",
                   inputs=[NodePort("in", "Message", "string")],
                   outputs=[NodePort("out", "Status", "object")]),
    NodeDefinition("tool_discord", "Discord", "Tool", "Send Discord message", "message", "#f59e0b",
                   inputs=[NodePort("in", "Message", "string")],
                   outputs=[NodePort("out", "Status", "object")]),
    NodeDefinition("tool_telegram", "Telegram", "Tool", "Send Telegram message", "send", "#f59e0b",
                   inputs=[NodePort("in", "Message", "string")],
                   outputs=[NodePort("out", "Status", "object")]),
    NodeDefinition("tool_twilio", "Twilio SMS", "Tool", "Send SMS via Twilio", "phone", "#f59e0b",
                   inputs=[NodePort("in", "Message", "string")],
                   outputs=[NodePort("out", "Status", "object")]),
    NodeDefinition("tool_github", "GitHub", "Tool", "GitHub API operations", "git", "#f59e0b",
                   inputs=[NodePort("in", "Config", "object")],
                   outputs=[NodePort("out", "Result", "object")]),
    NodeDefinition("tool_gitlab", "GitLab", "Tool", "GitLab API operations", "git", "#f59e0b",
                   inputs=[NodePort("in", "Config", "object")],
                   outputs=[NodePort("out", "Result", "object")]),
    NodeDefinition("tool_jira", "Jira", "Tool", "Jira issue management", "ticket", "#f59e0b",
                   inputs=[NodePort("in", "Config", "object")],
                   outputs=[NodePort("out", "Result", "object")]),
    NodeDefinition("tool_notion", "Notion", "Tool", "Notion API operations", "note", "#f59e0b",
                   inputs=[NodePort("in", "Config", "object")],
                   outputs=[NodePort("out", "Result", "object")]),
    NodeDefinition("tool_airtable", "Airtable", "Tool", "Airtable operations", "table", "#f59e0b",
                   inputs=[NodePort("in", "Config", "object")],
                   outputs=[NodePort("out", "Result", "object")]),
    NodeDefinition("tool_sheets", "Google Sheets", "Tool", "Google Sheets operations", "table", "#f59e0b",
                   inputs=[NodePort("in", "Config", "object")],
                   outputs=[NodePort("out", "Result", "object")]),

    # === LOGIC NODES (56-75) ===
    NodeDefinition("logic_condition", "Condition", "Logic", "If/else branching", "git-branch", "#ec4899",
                   inputs=[NodePort("in", "Value", "any"), NodePort("cond", "Condition", "object", False)],
                   outputs=[NodePort("true", "True", "any"), NodePort("false", "False", "any")],
                   config_schema={"operator": {"type": "string", "default": "equals"}, "compare_value": {"type": "any"}}),
    NodeDefinition("logic_switch", "Switch", "Logic", "Multi-way branching", "git-branch", "#ec4899",
                   inputs=[NodePort("in", "Value", "any")],
                   outputs=[NodePort("out0", "Case 0", "any"), NodePort("out1", "Case 1", "any"), NodePort("out2", "Case 2", "any"), NodePort("default", "Default", "any")],
                   config_schema={"cases": {"type": "array", "default": []}}),
    NodeDefinition("logic_loop", "Loop", "Logic", "Iterate over items", "repeat", "#ec4899",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("item", "Item", "any"), NodePort("index", "Index", "number"), NodePort("done", "Done", "array")]),
    NodeDefinition("logic_while", "While Loop", "Logic", "Loop while condition", "repeat", "#ec4899",
                   inputs=[NodePort("in", "Value", "any")],
                   outputs=[NodePort("body", "Body", "any"), NodePort("done", "Done", "any")],
                   config_schema={"condition": {"type": "string", "default": "less_than"}, "max_iterations": {"type": "number", "default": 100}}),
    NodeDefinition("logic_for_each", "For Each", "Logic", "Iterate and collect", "repeat", "#ec4899",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("item", "Item", "any"), NodePort("result", "Results", "array")]),
    NodeDefinition("logic_merge", "Merge", "Logic", "Merge multiple inputs", "git-merge", "#ec4899",
                   inputs=[NodePort("in0", "Input 0", "any"), NodePort("in1", "Input 1", "any")],
                   outputs=[NodePort("out", "Merged", "array")]),
    NodeDefinition("logic_delay", "Delay", "Logic", "Pause execution", "clock", "#ec4899",
                   inputs=[NodePort("in", "Value", "any")],
                   outputs=[NodePort("out", "Value", "any")],
                   config_schema={"duration": {"type": "number", "default": 1}, "unit": {"type": "string", "default": "seconds"}}),
    NodeDefinition("logic_wait_for", "Wait For", "Logic", "Wait for event", "clock", "#ec4899",
                   inputs=[NodePort("in", "Trigger", "any")],
                   outputs=[NodePort("out", "Value", "any")],
                   config_schema={"timeout": {"type": "number", "default": 60}}),
    NodeDefinition("logic_parallel", "Parallel", "Logic", "Run branches in parallel", "columns", "#ec4899",
                   inputs=[NodePort("in", "Value", "any")],
                   outputs=[NodePort("out0", "Branch 0", "any"), NodePort("out1", "Branch 1", "any"), NodePort("out2", "Branch 2", "any")]),
    NodeDefinition("logic_race", "Race", "Logic", "First result wins", "zap", "#ec4899",
                   inputs=[NodePort("in0", "Branch 0", "any"), NodePort("in1", "Branch 1", "any")],
                   outputs=[NodePort("out", "Winner", "any")]),
    NodeDefinition("logic_catch", "Error Handler", "Logic", "Catch and handle errors", "shield", "#ec4899",
                   inputs=[NodePort("in", "Value", "any")],
                   outputs=[NodePort("success", "Success", "any"), NodePort("error", "Error", "object")]),
    NodeDefinition("logic_noop", "No-Op", "Logic", "Pass-through (debug)", "minus", "#ec4899",
                   inputs=[NodePort("in", "Value", "any")],
                   outputs=[NodePort("out", "Value", "any")]),
    NodeDefinition("logic_comment", "Comment", "Logic", "Add a comment/sticky note", "message", "#ec4899",
                   inputs=[],
                   outputs=[],
                   config_schema={"text": {"type": "string", "default": ""}}),
    NodeDefinition("logic_trigger", "Manual Trigger", "Logic", "Manual execution trigger", "play", "#ec4899",
                   outputs=[NodePort("out", "Trigger", "any")]),
    NodeDefinition("logic_cron", "Cron Trigger", "Logic", "Schedule-based trigger", "clock", "#ec4899",
                   outputs=[NodePort("out", "Trigger", "any")],
                   config_schema={"schedule": {"type": "string", "default": "0 * * * *"}}),
    NodeDefinition("logic_webhook_trigger", "Webhook Trigger", "Logic", "HTTP webhook trigger", "link", "#ec4899",
                   outputs=[NodePort("out", "Payload", "object")],
                   config_schema={"path": {"type": "string", "default": "/webhook"}}),
    NodeDefinition("logic_event_trigger", "Event Trigger", "Logic", "Listen for events", "radio", "#ec4899",
                   outputs=[NodePort("out", "Event", "object")],
                   config_schema={"event": {"type": "string", "default": ""}}),
    NodeDefinition("logic_batch", "Batch", "Logic", "Batch process items", "layers", "#ec4899",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "Batch", "array")],
                   config_schema={"batch_size": {"type": "number", "default": 10}}),
    NodeDefinition("logic_debounce", "Debounce", "Logic", "Debounce rapid triggers", "clock", "#ec4899",
                   inputs=[NodePort("in", "Value", "any")],
                   outputs=[NodePort("out", "Value", "any")],
                   config_schema={"delay_ms": {"type": "number", "default": 500}}),
    NodeDefinition("logic_throttle", "Throttle", "Logic", "Throttle execution rate", "clock", "#ec4899",
                   inputs=[NodePort("in", "Value", "any")],
                   outputs=[NodePort("out", "Value", "any")],
                   config_schema={"interval_ms": {"type": "number", "default": 1000}}),

    # === TRANSFORM NODES (76-90) ===
    NodeDefinition("transform_map", "Map", "Transform", "Transform each item", "repeat", "#06b6d4",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "Results", "array")],
                   config_schema={"expression": {"type": "string", "default": "item"}}),
    NodeDefinition("transform_filter", "Filter", "Transform", "Filter items by condition", "filter", "#06b6d4",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "Filtered", "array")],
                   config_schema={"condition": {"type": "string", "default": "item != null"}}),
    NodeDefinition("transform_reduce", "Reduce", "Transform", "Reduce items to single value", "layers", "#06b6d4",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "Result", "any")],
                   config_schema={"expression": {"type": "string", "default": "acc + item"}}),
    NodeDefinition("transform_sort", "Sort", "Transform", "Sort items", "arrow-down", "#06b6d4",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "Sorted", "array")],
                   config_schema={"key": {"type": "string", "default": ""}, "order": {"type": "string", "default": "asc"}}),
    NodeDefinition("transform_group", "Group By", "Transform", "Group items by key", "layers", "#06b6d4",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "Groups", "object")],
                   config_schema={"key": {"type": "string", "default": ""}}),
    NodeDefinition("transform_flatten", "Flatten", "Transform", "Flatten nested arrays", "layers", "#06b6d4",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "Flattened", "array")]),
    NodeDefinition("transform_unique", "Unique", "Transform", "Remove duplicates", "filter", "#06b6d4",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "Unique", "array")]),
    NodeDefinition("transform_join", "Join", "Transform", "Join array to string", "type", "#06b6d4",
                   inputs=[NodePort("in", "Items", "array")],
                   outputs=[NodePort("out", "String", "string")],
                   config_schema={"separator": {"type": "string", "default": ", "}}),
    NodeDefinition("transform_split", "Split", "Transform", "Split string to array", "type", "#06b6d4",
                   inputs=[NodePort("in", "Text", "string")],
                   outputs=[NodePort("out", "Parts", "array")],
                   config_schema={"separator": {"type": "string", "default": ","}}),
    NodeDefinition("transform_template", "Template", "Transform", "Render template string", "code", "#06b6d4",
                   inputs=[NodePort("in", "Data", "object")],
                   outputs=[NodePort("out", "Rendered", "string")],
                   config_schema={"template": {"type": "string", "default": "{{data}}"}}),
    NodeDefinition("transform_json_parse", "JSON Parse", "Transform", "Parse JSON string", "code", "#06b6d4",
                   inputs=[NodePort("in", "JSON", "string")],
                   outputs=[NodePort("out", "Object", "object")]),
    NodeDefinition("transform_json_stringify", "JSON Stringify", "Transform", "Convert to JSON", "code", "#06b6d4",
                   inputs=[NodePort("in", "Object", "object")],
                   outputs=[NodePort("out", "JSON", "string")]),
    NodeDefinition("transform_regex", "Regex", "Transform", "Regex match/replace", "code", "#06b6d4",
                   inputs=[NodePort("in", "Text", "string")],
                   outputs=[NodePort("out", "Result", "array")],
                   config_schema={"pattern": {"type": "string"}, "action": {"type": "string", "default": "match"}}),
    NodeDefinition("transform_date_format", "Date Format", "Transform", "Format date/time", "calendar", "#06b6d4",
                   inputs=[NodePort("in", "Date", "string")],
                   outputs=[NodePort("out", "Formatted", "string")],
                   config_schema={"format": {"type": "string", "default": "YYYY-MM-DD"}}),
    NodeDefinition("transform_hash", "Hash", "Transform", "Generate hash", "lock", "#06b6d4",
                   inputs=[NodePort("in", "Value", "string")],
                   outputs=[NodePort("out", "Hash", "string")],
                   config_schema={"algorithm": {"type": "string", "default": "sha256"}}),

    # === DATA NODES (91-105) ===
    NodeDefinition("data_csv_parse", "CSV Parse", "Data", "Parse CSV data", "table", "#84cc16",
                   inputs=[NodePort("in", "CSV", "string")],
                   outputs=[NodePort("out", "Data", "array")],
                   config_schema={"delimiter": {"type": "string", "default": ","}, "header": {"type": "boolean", "default": True}}),
    NodeDefinition("data_csv_generate", "CSV Generate", "Data", "Generate CSV from data", "table", "#84cc16",
                   inputs=[NodePort("in", "Data", "array")],
                   outputs=[NodePort("out", "CSV", "string")]),
    NodeDefinition("data_xml_parse", "XML Parse", "Data", "Parse XML data", "code", "#84cc16",
                   inputs=[NodePort("in", "XML", "string")],
                   outputs=[NodePort("out", "Object", "object")]),
    NodeDefinition("data_yaml_parse", "YAML Parse", "Data", "Parse YAML data", "code", "#84cc16",
                   inputs=[NodePort("in", "YAML", "string")],
                   outputs=[NodePort("out", "Object", "object")]),
    NodeDefinition("data_base64_encode", "Base64 Encode", "Data", "Encode to Base64", "lock", "#84cc16",
                   inputs=[NodePort("in", "Value", "string")],
                   outputs=[NodePort("out", "Encoded", "string")]),
    NodeDefinition("data_base64_decode", "Base64 Decode", "Data", "Decode from Base64", "unlock", "#84cc16",
                   inputs=[NodePort("in", "Encoded", "string")],
                   outputs=[NodePort("out", "Decoded", "string")]),
    NodeDefinition("data_url_encode", "URL Encode", "Data", "URL encode string", "link", "#84cc16",
                   inputs=[NodePort("in", "Value", "string")],
                   outputs=[NodePort("out", "Encoded", "string")]),
    NodeDefinition("data_url_decode", "URL Decode", "Data", "URL decode string", "link", "#84cc16",
                   inputs=[NodePort("in", "Encoded", "string")],
                   outputs=[NodePort("out", "Decoded", "string")]),
    NodeDefinition("data_encrypt", "Encrypt", "Data", "Encrypt data", "lock", "#84cc16",
                   inputs=[NodePort("in", "Data", "string")],
                   outputs=[NodePort("out", "Encrypted", "string")],
                   config_schema={"algorithm": {"type": "string", "default": "aes-256-gcm"}}),
    NodeDefinition("data_decrypt", "Decrypt", "Data", "Decrypt data", "unlock", "#84cc16",
                   inputs=[NodePort("in", "Encrypted", "string")],
                   outputs=[NodePort("out", "Decrypted", "string")]),
    NodeDefinition("data_compress", "Compress", "Data", "Compress data", "archive", "#84cc16",
                   inputs=[NodePort("in", "Data", "string")],
                   outputs=[NodePort("out", "Compressed", "string")],
                   config_schema={"algorithm": {"type": "string", "default": "gzip"}}),
    NodeDefinition("data_decompress", "Decompress", "Data", "Decompress data", "archive", "#84cc16",
                   inputs=[NodePort("in", "Compressed", "string")],
                   outputs=[NodePort("out", "Decompressed", "string")]),
    NodeDefinition("data_diff", "Diff", "Data", "Compare two values", "git-compare", "#84cc16",
                   inputs=[NodePort("a", "Value A", "any"), NodePort("b", "Value B", "any")],
                   outputs=[NodePort("out", "Diff", "object")]),
    NodeDefinition("data_merge_objects", "Merge Objects", "Data", "Deep merge objects", "git-merge", "#84cc16",
                   inputs=[NodePort("a", "Object A", "object"), NodePort("b", "Object B", "object")],
                   outputs=[NodePort("out", "Merged", "object")]),
    NodeDefinition("data_pick_keys", "Pick Keys", "Data", "Pick specific keys from object", "filter", "#84cc16",
                   inputs=[NodePort("in", "Object", "object")],
                   outputs=[NodePort("out", "Result", "object")],
                   config_schema={"keys": {"type": "array", "default": []}}),

    # === ADVANCED NODES (106-120) ===
    NodeDefinition("agent_react", "ReAct Agent", "Agent", "Reasoning + Acting agent", "bot", "#7c3aed",
                   inputs=[NodePort("in", "Task", "string")],
                   outputs=[NodePort("out", "Result", "string"), NodePort("steps", "Steps", "array")],
                   config_schema={"max_steps": {"type": "number", "default": 10}}),
    NodeDefinition("agent_planner", "Planner Agent", "Agent", "Plan-and-execute agent", "bot", "#7c3aed",
                   inputs=[NodePort("in", "Goal", "string")],
                   outputs=[NodePort("out", "Result", "string"), NodePort("plan", "Plan", "array")]),
    NodeDefinition("agent_critic", "Critic Agent", "Agent", "Self-critiquing agent", "bot", "#7c3aed",
                   inputs=[NodePort("in", "Content", "string")],
                   outputs=[NodePort("out", "Critique", "string"), NodePort("score", "Score", "number")]),
    NodeDefinition("agent_router", "Router Agent", "Agent", "Route to specialized agent", "git-branch", "#7c3aed",
                   inputs=[NodePort("in", "Input", "string")],
                   outputs=[NodePort("out", "Result", "string")],
                   config_schema={"agents": {"type": "array", "default": []}}),
    NodeDefinition("agent_memory", "Memory Agent", "Agent", "Agent with memory", "database", "#7c3aed",
                   inputs=[NodePort("in", "Input", "string")],
                   outputs=[NodePort("out", "Response", "string")],
                   config_schema={"memory_type": {"type": "string", "default": "conversation"}}),
    NodeDefinition("rag_query", "RAG Query", "RAG", "Retrieval-augmented generation", "search", "#7c3aed",
                   inputs=[NodePort("in", "Query", "string")],
                   outputs=[NodePort("out", "Answer", "string"), NodePort("sources", "Sources", "array")],
                   config_schema={"top_k": {"type": "number", "default": 5}}),
    NodeDefinition("rag_index", "RAG Index", "RAG", "Index documents for RAG", "database", "#7c3aed",
                   inputs=[NodePort("in", "Documents", "array")],
                   outputs=[NodePort("out", "Status", "object")]),
    NodeDefinition("rag_embed", "Embed Text", "RAG", "Generate embeddings", "vector", "#7c3aed",
                   inputs=[NodePort("in", "Text", "string")],
                   outputs=[NodePort("out", "Embedding", "array")]),
    NodeDefinition("vision_image_gen", "Image Generation", "Vision", "Generate images", "image", "#7c3aed",
                   inputs=[NodePort("in", "Prompt", "string")],
                   outputs=[NodePort("out", "Image", "string")],
                   config_schema={"provider": {"type": "string", "default": "dall-e"}, "size": {"type": "string", "default": "1024x1024"}}),
    NodeDefinition("vision_image_analyze", "Image Analysis", "Vision", "Analyze images", "eye", "#7c3aed",
                   inputs=[NodePort("in", "Image", "string")],
                   outputs=[NodePort("out", "Analysis", "string")]),
    NodeDefinition("vision_ocr", "OCR", "Vision", "Extract text from image", "text", "#7c3aed",
                   inputs=[NodePort("in", "Image", "string")],
                   outputs=[NodePort("out", "Text", "string")]),
    NodeDefinition("audio_transcribe", "Transcribe", "Audio", "Speech to text", "mic", "#7c3aed",
                   inputs=[NodePort("in", "Audio", "string")],
                   outputs=[NodePort("out", "Text", "string")]),
    NodeDefinition("audio_tts", "Text to Speech", "Audio", "Text to speech", "volume", "#7c3aed",
                   inputs=[NodePort("in", "Text", "string")],
                   outputs=[NodePort("out", "Audio", "string")]),
    NodeDefinition("audio_translate", "Translate Audio", "Audio", "Translate speech", "globe", "#7c3aed",
                   inputs=[NodePort("in", "Audio", "string")],
                   outputs=[NodePort("out", "Translation", "string")]),
    NodeDefinition("custom_python", "Custom Python", "Custom", "Write custom Python code", "code", "#64748b",
                   inputs=[NodePort("in", "Input", "any")],
                   outputs=[NodePort("out", "Output", "any")],
                   config_schema={"code": {"type": "string", "default": "return input"}}),
]


def get_node_registry() -> dict[str, NodeDefinition]:
    """Get all node definitions as a dict keyed by type."""
    return {n.type: n for n in NODE_DEFINITIONS}


def get_nodes_by_category() -> dict[str, list[NodeDefinition]]:
    """Get nodes grouped by category."""
    cats: dict[str, list[NodeDefinition]] = {}
    for n in NODE_DEFINITIONS:
        cats.setdefault(n.category, []).append(n)
    return cats


def get_node(type_name: str) -> NodeDefinition | None:
    """Get a single node definition by type."""
    return get_node_registry().get(type_name)
