"""Core data models for the DeepResearch Engine."""
from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class AgentType(str, Enum):
    """Types of specialized research agents."""

    LITERATURE_REVIEWER = "literature_reviewer"
    HYPOTHESIS_GENERATOR = "hypothesis_generator"
    EXPERIMENT_DESIGNER = "experiment_designer"
    PAPER_WRITER = "paper_writer"


class ResearchStage(str, Enum):
    """Stages of the research pipeline."""

    SEARCH = "search"
    READ = "read"
    SYNTHESIZE = "synthesize"
    HYPOTHESIZE = "hypothesize"
    VALIDATE = "validate"
    WRITE = "write"
    COMPLETE = "complete"


class PaperStatus(str, Enum):
    """Status of a paper in the pipeline."""

    PENDING = "pending"
    FETCHED = "fetched"
    ANALYZED = "analyzed"
    ARCHIVED = "archived"


class Source(str, Enum):
    """Data source for papers."""

    ARXIV = "arxiv"
    PUBMED = "pubmed"
    CROSSREF = "crossref"


class Citation(BaseModel):
    """A single citation relationship."""

    paper_id: str
    cited_by: str
    context: Optional[str] = None


class Paper(BaseModel):
    """Represents a research paper."""

    id: str
    title: str
    authors: list[str] = Field(default_factory=list)
    abstract: str = ""
    year: int = 2024
    source: Source = Source.ARXIV
    url: Optional[str] = None
    doi: Optional[str] = None
    keywords: list[str] = Field(default_factory=list)
    references: list[str] = Field(default_factory=list)
    status: PaperStatus = PaperStatus.PENDING
    content: Optional[str] = None
    embedding: Optional[list[float]] = None

    def cite(self) -> str:
        """Return a formatted citation string."""
        author_str = ", ".join(self.authors[:3])
        if len(self.authors) > 3:
            author_str += " et al."
        return f"{author_str} ({self.year}). {self.title}. {self.source.value}."


class Hypothesis(BaseModel):
    """A research hypothesis generated from literature."""

    id: str
    statement: str
    confidence: float = Field(ge=0.0, le=1.0)
    supporting_papers: list[str] = Field(default_factory=list)
    contradicting_papers: list[str] = Field(default_factory=list)
    gap_description: str = ""
    novelty_score: float = Field(default=0.0, ge=0.0, le=1.0)

    def to_prompt(self) -> str:
        """Format hypothesis for LLM consumption."""
        return (
            f"Hypothesis: {self.statement}\n"
            f"Confidence: {self.confidence:.2f}\n"
            f"Novelty: {self.novelty_score:.2f}\n"
            f"Gap: {self.gap_description}\n"
            f"Supporting: {len(self.supporting_papers)} papers\n"
            f"Contradicting: {len(self.contradicting_papers)} papers"
        )


class ExperimentDesign(BaseModel):
    """An experiment designed to test a hypothesis."""

    id: str
    hypothesis_id: str
    title: str
    description: str
    methodology: str
    variables: list[str] = Field(default_factory=list)
    expected_outcome: str
    feasibility_score: float = Field(default=0.5, ge=0.0, le=1.0)
    simulation_code: Optional[str] = None

    def to_markdown(self) -> str:
        """Render experiment as Markdown."""
        return (
            f"## {self.title}\n\n"
            f"**Description:** {self.description}\n\n"
            f"**Methodology:** {self.methodology}\n\n"
            f"**Variables:** {', '.join(self.variables)}\n\n"
            f"**Expected Outcome:** {self.expected_outcome}\n\n"
            f"**Feasibility:** {self.feasibility_score:.2f}"
        )


class SynthesisResult(BaseModel):
    """Result of synthesizing a set of papers."""

    themes: list[str] = Field(default_factory=list)
    key_findings: list[str] = Field(default_factory=list)
    contradictions: list[str] = Field(default_factory=list)
    knowledge_gaps: list[str] = Field(default_factory=list)
    citation_network_insights: list[str] = Field(default_factory=list)


class ResearchPlan(BaseModel):
    """A full research plan generated by the engine."""

    query: str
    stage: ResearchStage = ResearchStage.SEARCH
    papers: list[Paper] = Field(default_factory=list)
    synthesis: Optional[SynthesisResult] = None
    hypotheses: list[Hypothesis] = Field(default_factory=list)
    experiments: list[ExperimentDesign] = Field(default_factory=list)
    final_paper: Optional[str] = None

    @property
    def progress(self) -> dict[str, Any]:
        """Return progress metrics."""
        return {
            "papers_count": len(self.papers),
            "hypotheses_count": len(self.hypotheses),
            "experiments_count": len(self.experiments),
            "stage": self.stage.value,
            "has_synthesis": self.synthesis is not None,
            "has_paper": self.final_paper is not None,
        }
