"""Simple test runner that doesn't use pytest - covers all AgentOS modules."""
import sys
import traceback

passed = 0
failed = 0

def assert_test(condition, name):
    global passed, failed
    if condition:
        print(f"  PASS: {name}")
        passed += 1
    else:
        print(f"  FAIL: {name}")
        failed += 1

# ============================================================
print("\n=== Testing governor ===")
from agentos.governor import RateLimiter, ResourceGovernor, ResourceLimits, ResourceUsage

# TestRateLimiter
limiter = RateLimiter(max_requests=5, window_seconds=60.0)
for _ in range(5):
    assert_test(limiter.allow() is True, "RateLimiter allows within limit")
    limiter.record()
limiter = RateLimiter(max_requests=2, window_seconds=60.0)
limiter.record()
limiter.record()
assert_test(limiter.allow() is False, "RateLimiter blocks over limit")
limiter = RateLimiter(max_requests=5, window_seconds=60.0)
limiter.record()
limiter.record()
assert_test(limiter.remaining() == 3, "RateLimiter remaining count")
limiter = RateLimiter(max_requests=2, window_seconds=60.0)
limiter.record()
limiter.record()
limiter.reset()
assert_test(limiter.allow() is True, "RateLimiter reset")
assert_test(limiter.remaining() == 2, "RateLimiter remaining after reset")
print("  TestRateLimiter: PASS")

# TestResourceGovernor
governor = ResourceGovernor()
governor.register_tenant("t1")
assert_test(governor.get_usage("t1") is not None, "Register tenant")
governor = ResourceGovernor(ResourceLimits(max_cpu=2.0))
governor.register_tenant("t1")
assert_test(governor.allocate_cpu("t1", 1.0) is True, "Allocate CPU within limit")
assert_test(governor.get_usage("t1").cpu == 1.0, "CPU usage tracked")
governor = ResourceGovernor(ResourceLimits(max_cpu=2.0))
governor.register_tenant("t1")
assert_test(governor.allocate_cpu("t1", 3.0) is False, "Reject CPU over limit")
governor = ResourceGovernor(ResourceLimits(max_cpu=2.0))
governor.register_tenant("t1")
governor.allocate_cpu("t1", 1.5)
governor.release_cpu("t1", 0.5)
assert_test(abs(governor.get_usage("t1").cpu - 1.0) < 0.001, "Release CPU")
governor = ResourceGovernor(ResourceLimits(max_memory=1024))
governor.register_tenant("t1")
assert_test(governor.allocate_memory("t1", 512) is True, "Allocate memory within limit")
governor = ResourceGovernor(ResourceLimits(max_memory=1024))
governor.register_tenant("t1")
assert_test(governor.allocate_memory("t1", 2048) is False, "Reject memory over limit")
governor = ResourceGovernor(ResourceLimits(max_memory=1024))
governor.register_tenant("t1")
governor.allocate_memory("t1", 512)
governor.release_memory("t1", 256)
assert_test(governor.get_usage("t1").memory == 256, "Release memory")
governor = ResourceGovernor(ResourceLimits(max_api_requests_per_minute=2))
governor.register_tenant("t1")
assert_test(governor.record_api_request("t1") is True, "API rate 1st request")
assert_test(governor.record_api_request("t1") is True, "API rate 2nd request")
assert_test(governor.record_api_request("t1") is False, "API rate 3rd blocked")
governor = ResourceGovernor()
assert_test(governor.get_usage("unknown") is None, "Unknown tenant usage")
assert_test(governor.allocate_cpu("unknown", 1.0) is False, "Unknown tenant allocate")
print("  TestResourceGovernor: PASS")

# ============================================================
print("\n=== Testing state ===")
from agentos.state import StateEntry, StateError, StateManager

state = StateManager()
assert_test(state is not None, "Create in-memory")
state = StateManager()
state.set("key1", "value1")
assert_test(state.get("key1") == "value1", "Set and get")
state = StateManager()
data = {"nested": {"key": [1, 2, 3]}, "flag": True}
state.set("complex", data)
assert_test(state.get("complex") == data, "Set complex value")
state = StateManager()
state.set("key", "old")
state.set("key", "new")
assert_test(state.get("key") == "new", "Update existing")
state = StateManager()
assert_test(state.get("nonexistent") is None, "Get nonexistent")
state = StateManager()
state.set("key", "value")
assert_test(state.delete("key") is True, "Delete")
assert_test(state.get("key") is None, "Deleted key is None")
state = StateManager()
assert_test(state.delete("nonexistent") is False, "Delete nonexistent")
state = StateManager()
state.set("a", 1)
state.set("ab", 2)
state.set("abc", 3)
keys = state.list_keys()
assert_test(sorted(keys) == ["a", "ab", "abc"], "List keys")
state = StateManager()
state.set("prefix_key1", 1)
state.set("prefix_key2", 2)
state.set("other", 3)
keys = state.list_keys(prefix="prefix_")
assert_test(sorted(keys) == ["prefix_key1", "prefix_key2"], "List keys with prefix")
state = StateManager()
state.set("key", "tenant1_value", tenant_id="t1")
state.set("key", "tenant2_value", tenant_id="t2")
assert_test(state.get("key", tenant_id="t1") == "tenant1_value", "Tenant isolation t1")
assert_test(state.get("key", tenant_id="t2") == "tenant2_value", "Tenant isolation t2")
state = StateManager()
state.set("a", 1, tenant_id="t1")
state.set("b", 2, tenant_id="t1")
state.set("c", 3, tenant_id="t2")
deleted = state.clear_tenant("t1")
assert_test(deleted == 2, "Clear tenant count")
assert_test(state.get("c", tenant_id="t2") == 3, "Clear tenant preserves other")
state = StateManager()
state.set("key", "v1")
state.set("key", "v2")
history = state.get_history("key")
assert_test(len(history) == 2, "History logged")
state = StateManager()
state.set("key", "value")
state.close()
try:
    state.get("key")
    assert_test(False, "Close raises StateError")
except StateError as e:
    assert_test("Database connection is closed" in str(e), "Close raises StateError")
with StateManager() as state:
    state.set("key", "value")
    assert_test(state.get("key") == "value", "Context manager")
print("  TestStateManager: PASS")

# ============================================================
print("\n=== Testing bus ===")
from agentos.bus import Bus, BusError, Message

msg = Message(topic="test", payload="data")
assert_test(msg.topic == "test", "Create message")
assert_test(msg.payload == "data", "Message payload")
assert_test(msg.message_id is not None, "Message ID auto-generated")
msg = Message(topic="test", payload={"key": "value"}, sender="agent1")
json_str = msg.to_json()
restored = Message.from_json(json_str)
assert_test(restored.topic == msg.topic, "Serialize/deserialize topic")
assert_test(restored.payload == msg.payload, "Serialize/deserialize payload")
assert_test(restored.sender == msg.sender, "Serialize/deserialize sender")
msg = Message(topic="test", payload="data", headers={"rpc": "true"})
assert_test(msg.headers["rpc"] == "true", "Message with headers")
bus = Bus()
received = []
bus.subscribe("test.topic", lambda m: received.append(m))
bus.publish(Message(topic="test.topic", payload="hello"))
assert_test(len(received) == 1, "Publish/subscribe")
assert_test(received[0].payload == "hello", "Received payload")
bus = Bus()
count = [0]
def callback(m):
    count[0] += 1
bus.subscribe("topic", callback)
bus.subscribe("topic", callback)
bus.publish(Message(topic="topic", payload="data"))
assert_test(count[0] == 2, "Multiple subscribers")
bus = Bus()
delivered = bus.publish(Message(topic="empty", payload="data"))
assert_test(delivered == 0, "No subscribers")
bus = Bus()
bus.publish(Message(topic="t1", payload="a"))
bus.publish(Message(topic="t2", payload="b"))
history = bus.get_history(limit=10)
assert_test(len(history) == 2, "History")
bus = Bus()
bus.publish(Message(topic="t1", payload="a"))
bus.publish(Message(topic="t2", payload="b"))
history = bus.get_history(topic="t1")
assert_test(len(history) == 1, "History by topic")
assert_test(history[0].topic == "t1", "History topic filter")
bus = Bus()
bus.subscribe("topic1", lambda m: None)
bus.subscribe("topic2", lambda m: None)
assert_test(sorted(bus.topics()) == ["topic1", "topic2"], "Topics list")
bus = Bus()
bus.subscribe("topic", lambda m: None)
bus.subscribe("topic", lambda m: None)
assert_test(bus.subscriber_count("topic") == 2, "Subscriber count")
bus = Bus()
sub_id = bus.subscribe("topic", lambda m: None)
assert_test(bus.unsubscribe("topic", sub_id) is True, "Unsubscribe")
bus = Bus()
bus.subscribe("topic", lambda m: None)
bus.subscribe("topic", lambda m: None)
bus.subscribe("topic", lambda m: None)
count = bus.publish(Message(topic="topic", payload="data"))
assert_test(count == 3, "Publish returns delivery count")
print("  TestBus: PASS")

# ============================================================
print("\n=== Testing observability ===")
from agentos.observability import MetricsCollector, Observability, Span, Tracer

span = Span(trace_id="trace1", span_id="span1", parent_id=None, name="test", start_time=1000.0)
assert_test(span.name == "test", "Create span")
assert_test(span.duration_ms is None, "Span duration None before end")
span = Span(trace_id="trace1", span_id="span1", parent_id=None, name="test", start_time=1000.0)
span.end_time = 1001.5
assert_test(span.duration_ms == 1500.0, "Span duration calculated")
span = Span(trace_id="trace1", span_id="span1", parent_id="parent1", name="test", start_time=1000.0, end_time=1001.0, status="ok")
d = span.to_dict()
assert_test(d["name"] == "test", "Span to_dict name")
assert_test(d["status"] == "ok", "Span to_dict status")
tracer = Tracer()
span = tracer.start_span("test")
tracer.end_span(span.span_id)
assert_test(len(tracer.get_spans()) == 1, "Tracer start/end span")
tracer = Tracer()
with tracer.span("test") as span:
    assert_test(span.status == "unset", "Span context manager status during")
assert_test(span.status == "ok", "Span context manager status after")
tracer = Tracer()
try:
    with tracer.span("test") as span:
        raise ValueError("test error")
except ValueError:
    pass
assert_test(span.status == "error", "Span context manager error")
tracer = Tracer()
s1 = tracer.start_span("op1", trace_id="t1")
s2 = tracer.start_span("op2", trace_id="t2")
tracer.end_span(s1.span_id)
tracer.end_span(s2.span_id)
assert_test(len(tracer.get_spans("t1")) == 1, "Get spans by trace")
assert_test(len(tracer.get_spans("t2")) == 1, "Get spans by trace t2")
tracer = Tracer()
span = tracer.start_span("test")
tracer.end_span(span.span_id)
tracer.clear()
assert_test(len(tracer.get_spans()) == 0, "Clear spans")
metrics = MetricsCollector()
metrics.counter("requests")
metrics.counter("requests")
assert_test(metrics.get_counter("requests") == 2.0, "Counter")
metrics = MetricsCollector()
metrics.gauge("cpu_usage", 75.5)
assert_test(metrics.get_gauge("cpu_usage") == 75.5, "Gauge")
metrics = MetricsCollector()
metrics.histogram("latency", 100.0)
metrics.histogram("latency", 200.0)
h = metrics.get_metrics("latency", type="histogram")
assert_test(len(h) == 2, "Histogram")
metrics = MetricsCollector()
metrics.counter("c1", 5.0)
metrics.gauge("g1", 10.0)
metrics.histogram("h1", 1.0)
metrics.histogram("h1", 3.0)
summary = metrics.summary()
assert_test("counters" in summary, "Summary has counters")
assert_test("gauges" in summary, "Summary has gauges")
assert_test("histograms" in summary, "Summary has histograms")
assert_test(summary["histograms"]["h1"]["avg"] == 2.0, "Histogram avg")
metrics = MetricsCollector()
metrics.counter("requests", labels={"method": "GET", "status": "200"})
assert_test(metrics.get_counter("requests", labels={"method": "GET", "status": "200"}) == 1.0, "Metrics with labels")
metrics = MetricsCollector()
metrics.counter("test")
metrics.clear()
assert_test(metrics.get_counter("test") == 0, "Clear metrics")
obs = Observability()
with obs.trace("test_op"):
    pass
assert_test(len(obs.tracer.get_spans()) == 1, "Trace and metrics spans")
assert_test(len(obs.metrics.get_metrics("operation_duration_seconds")) == 1, "Trace and metrics duration")
obs = Observability()
health = obs.health()
assert_test(health["status"] == "healthy", "Health")
obs = Observability()
obs.record_error(ValueError("test"))
assert_test(obs.metrics.get_counter("errors_total", labels={"type": "ValueError"}) == 1.0, "Record error")
print("  TestObservability: PASS")

# ============================================================
print("\n=== Testing tenancy ===")
from agentos.governor import ResourceLimits
from agentos.tenancy import Tenant, TenantManager

tenant = Tenant(id="t1", name="Test Tenant")
assert_test(tenant.id == "t1", "Create tenant")
assert_test(tenant.name == "Test Tenant", "Tenant name")
assert_test(tenant.active is True, "Tenant active")
limits = ResourceLimits(max_cpu=2.0, max_memory=1024)
tenant = Tenant(id="t1", name="Test", limits=limits)
assert_test(tenant.limits.max_cpu == 2.0, "Tenant with limits")
manager = TenantManager()
tenant = manager.create_tenant("t1", "Test Tenant")
assert_test(tenant.id == "t1", "Create tenant via manager")
assert_test(tenant.name == "Test Tenant", "Manager tenant name")
manager = TenantManager()
manager.create_tenant("t1", "Test")
try:
    manager.create_tenant("t1", "Test 2")
    assert_test(False, "Duplicate tenant raises")
except ValueError as e:
    assert_test("already exists" in str(e), "Duplicate tenant raises")
manager = TenantManager()
manager.create_tenant("t1", "Test")
tenant = manager.get_tenant("t1")
assert_test(tenant is not None, "Get tenant")
assert_test(tenant.name == "Test", "Get tenant name")
manager = TenantManager()
manager.create_tenant("t1", "Test")
updated = manager.update_tenant("t1", name="Updated")
assert_test(updated.name == "Updated", "Update tenant")
manager = TenantManager()
manager.create_tenant("t1", "Test")
assert_test(manager.delete_tenant("t1") is True, "Delete tenant")
assert_test(manager.get_tenant("t1") is None, "Deleted tenant is None")
manager = TenantManager()
manager.create_tenant("t1", "Tenant 1")
manager.create_tenant("t2", "Tenant 2")
assert_test(len(manager.list_tenants()) == 2, "List tenants")
manager = TenantManager()
manager.create_tenant("t1", "Active")
manager.create_tenant("t2", "Inactive")
manager.suspend_tenant("t2")
active = manager.list_tenants(active_only=True)
assert_test(len(active) == 1, "List active tenants")
assert_test(active[0].id == "t1", "Active tenant id")
manager = TenantManager()
limits = ResourceLimits(max_cpu=2.0)
manager.create_tenant("t1", "Test", limits=limits)
assert_test(manager.check_quota("t1", "cpu", 1.0) is True, "Check quota CPU within")
assert_test(manager.check_quota("t1", "cpu", 3.0) is False, "Check quota CPU over")
manager = TenantManager()
limits = ResourceLimits(max_memory=1024)
manager.create_tenant("t1", "Test", limits=limits)
assert_test(manager.check_quota("t1", "memory", 512) is True, "Check quota memory within")
assert_test(manager.check_quota("t1", "memory", 2048) is False, "Check quota memory over")
manager = TenantManager()
limits = ResourceLimits(max_cpu=2.0)
manager.create_tenant("t1", "Test", limits=limits)
assert_test(manager.allocate("t1", "cpu", 1.0) is True, "Allocate CPU")
manager.release("t1", "cpu", 0.5)
usage = manager.get_usage("t1")
assert_test(usage is not None, "Get usage")
assert_test(abs(usage.cpu - 0.5) < 0.001, "Release CPU usage")
manager = TenantManager()
manager.create_tenant("t1", "Test")
assert_test(manager.suspend_tenant("t1") is True, "Suspend tenant")
tenant = manager.get_tenant("t1")
assert_test(tenant is not None, "Suspended tenant exists")
assert_test(tenant.active is False, "Suspended tenant inactive")
manager = TenantManager()
manager.create_tenant("t1", "Test")
manager.suspend_tenant("t1")
assert_test(manager.activate_tenant("t1") is True, "Activate tenant")
tenant = manager.get_tenant("t1")
assert_test(tenant is not None, "Activated tenant exists")
assert_test(tenant.active is True, "Activated tenant active")
manager = TenantManager()
assert_test(manager.check_quota("unknown", "cpu", 1.0) is False, "Unknown tenant quota")
print("  TestTenantManager: PASS")

# ============================================================
print("\n=== Testing sandbox ===")
from agentos.sandbox import Sandbox, SandboxConfig, SandboxResult

config = SandboxConfig()
assert_test(config.max_cpu_time == 30.0, "Default config max_cpu_time")
assert_test(config.max_memory_mb == 512, "Default config max_memory_mb")
assert_test(config.allow_network is False, "Default config allow_network")
config = SandboxConfig(max_cpu_time=10.0, allow_network=True)
assert_test(config.max_cpu_time == 10.0, "Custom config max_cpu_time")
assert_test(config.allow_network is True, "Custom config allow_network")
result = SandboxResult(returncode=0, stdout="output", stderr="", duration=1.5, memory_used_mb=128)
assert_test(result.returncode == 0, "Create result")
assert_test(result.timed_out is False, "Result timed_out False")
sandbox = Sandbox()
assert_test(sandbox.config.max_cpu_time == 30.0, "Create sandbox")
sandbox = Sandbox(SandboxConfig(allow_write=True))
result = sandbox.run(["echo", "hello"])
assert_test(result.returncode == 0, "Run echo returncode")
assert_test("hello" in result.stdout, "Run echo stdout")
sandbox = Sandbox(SandboxConfig(max_cpu_time=1.0))
result = sandbox.run(["echo", "fast"])
assert_test(result.timed_out is False, "Run with timeout not timed out")
sandbox = Sandbox()
path = sandbox.create_isolated_dir()
assert_test(path.exists(), "Create isolated dir exists")
assert_test(path.is_dir(), "Create isolated dir is dir")
path.rmdir()
print("  TestSandbox: PASS")

# ============================================================
print("\n=== Testing plugins ===")
from agentos.plugins import Plugin, PluginError, PluginManager, PluginManifest

manifest = PluginManifest(name="test-plugin", version="1.0.0", description="A test plugin")
assert_test(manifest.name == "test-plugin", "Create manifest")
assert_test(manifest.version == "1.0.0", "Manifest version")
manifest = PluginManifest(name="test", version="1.0.0", permissions=["read"])
d = manifest.to_dict()
assert_test(d["name"] == "test", "Manifest to_dict name")
assert_test(d["permissions"] == ["read"], "Manifest to_dict permissions")
data = {"name": "test", "version": "1.0.0", "description": "desc"}
manifest = PluginManifest.from_dict(data)
assert_test(manifest.name == "test", "Manifest from_dict name")
manager = PluginManager()
assert_test(manager is not None, "Create manager")
manager = PluginManager()
manifest = PluginManifest(name="test", version="1.0.0", description="Test plugin")
plugin = manager.load_from_manifest(manifest)
assert_test(plugin.manifest.name == "test", "Load from manifest name")
assert_test(plugin.loaded is True, "Load from manifest loaded")
manager = PluginManager()
manifest = PluginManifest(name="test", version="1.0.0")
manager.load_from_manifest(manifest)
plugin = manager.get("test")
assert_test(plugin is not None, "Get plugin")
assert_test(plugin.manifest.name == "test", "Get plugin name")
manager = PluginManager()
manager.load_from_manifest(PluginManifest(name="p1", version="1.0.0"))
manager.load_from_manifest(PluginManifest(name="p2", version="1.0.0"))
assert_test(len(manager.list_plugins()) == 2, "List plugins")
manager = PluginManager()
manager.load_from_manifest(PluginManifest(name="test", version="1.0.0"))
assert_test(manager.unload("test") is True, "Unload plugin")
assert_test(manager.get("test") is None, "Unloaded plugin is None")
manager = PluginManager()
try:
    manager.execute("nonexistent", None)
    assert_test(False, "Execute nonexistent raises")
except PluginError as e:
    assert_test("Plugin not found" in str(e), "Execute nonexistent raises")
manager = PluginManager()
manifest = PluginManifest(name="test", version="1.0.0", permissions=["read", "write"])
manager.load_from_manifest(manifest)
issues = manager.validate("test")
assert_test(len(issues) == 0, "Validate plugin")
manager = PluginManager()
manifest = PluginManifest(name="dangerous", version="1.0.0", permissions=["filesystem.write", "network.raw"])
manager.load_from_manifest(manifest)
issues = manager.validate("dangerous")
assert_test(len(issues) == 2, "Validate dangerous permissions")
manager = PluginManager()
events = []
manager.register_hook("loaded", lambda p: events.append(p.manifest.name))
manager.load_from_manifest(PluginManifest(name="test", version="1.0.0"))
assert_test(events == ["test"], "Register hook")
print("  TestPluginManager: PASS")

# ============================================================
print("\n=== Testing CLI ===")
from click.testing import CliRunner
from agentos.cli import main

runner = CliRunner()
result = runner.invoke(main, ["--version"])
assert_test(result.exit_code == 0, "CLI version exit_code")
assert_test("1.0.0" in result.output, "CLI version output")
runner = CliRunner()
result = runner.invoke(main, ["status"])
assert_test(result.exit_code == 0, "CLI status exit_code")
assert_test("running" in result.output, "CLI status output")
runner = CliRunner()
result = runner.invoke(main, ["self-test"])
assert_test(result.exit_code == 0, "CLI self-test exit_code")
assert_test("PASS" in result.output, "CLI self-test output")
runner = CliRunner()
result = runner.invoke(main, ["submit", "test-agent", "--priority", "high"])
assert_test(result.exit_code == 0, "CLI submit exit_code")
assert_test("submitted" in result.output, "CLI submit output")
runner = CliRunner()
result = runner.invoke(main, ["metrics"])
assert_test(result.exit_code == 0, "CLI metrics exit_code")
print("  TestCLI: PASS")

# ============================================================
print(f"\n{'='*60}")
print(f"TOTAL: {passed} passed, {failed} failed")
if failed > 0:
    sys.exit(1)
print("ALL TESTS PASSED")
