/**
 * Build verification manifest for AVOStudio Phase 3.
 * Generated by agent-architect session t_7627aaba.
 *
 * This file documents what was built and what needs shell execution.
 */

export const BUILD_MANIFEST = {
  phase: 3,
  project: 'hermes-avo',
  component: 'AVOStudio',
  files: {
    src: [
      'main.tsx',
      'App.tsx',
      'index.css',
      'types/trace.ts',
      'lib/api.ts',
      'lib/sse.ts',
      'store/studioStore.ts',
      'store/StoreProvider.tsx',
      'components/ConnectionStatus.tsx',
      'components/StatusBadge.tsx',
      'components/ChatInterface.tsx',
      'components/CircuitBreakersDashboard.tsx',
      'components/StatusBadge.tsx',
      'views/AgentGridView.tsx',
      'views/PlanVisualization.tsx',
      'views/TraceGraphView.tsx',
    ],
    tests: [
      'src/components/__tests__/StatusBadge.test.tsx',
      'src/components/__tests__/AgentGrid.test.tsx',
      'src/components/__tests__/PlanVisualization.test.tsx',
      'src/components/__tests__/TraceGraph.test.tsx',
      'src/components/__tests__/ChatInterface.test.tsx',
      'src/components/__tests__/CircuitBreakers.test.tsx',
      'src/lib/__tests__/sse.test.ts',
      'src/lib/__tests__/api.test.ts',
      'src/store/__tests__/studioStore.test.ts',
      'tests/components/ConnectionStatus.test.tsx',
    ],
    config: [
      'package.json',
      'tsconfig.json',
      'tsconfig.node.json',
      'vite.config.ts',
      'tailwind.config.js',
      'postcss.config.cjs',
      '.eslintrc.cjs',
      '.gitignore',
      'index.html',
      'favicon.svg',
    ],
  },
  testCount: 79, // 5+7+6+8+11+9+8+9+9+7 = 79 test cases across 10 files
  testTarget: 17, // minimum required
  buildTarget: 'vite build',
  testCommand: 'npm test',
  needsShell: true, // npm install, vitest, vite build, git commit
} as const;

export default BUILD_MANIFEST;
