"""API routes for workflow CRUD and execution."""
from __future__ import annotations

from typing import Any
from uuid import uuid4

from fastapi import APIRouter, HTTPException

from app.models.schemas import (
    Workflow, WorkflowNode, WorkflowEdge, Position,
    WorkflowExecution, ExportRequest, DeployRequest,
)
from app.nodes.registry import get_node_registry, get_nodes_by_category, get_node
from app.services.engine import ExecutionEngine

router = APIRouter()

# In-memory store for workflows
_workflows: dict[str, Workflow] = {}


@router.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok", "service": "ChainForge", "version": "1.0.0"}


@router.get("/nodes")
async def list_nodes() -> dict[str, Any]:
    """List all node definitions grouped by category."""
    return get_nodes_by_category()


@router.get("/nodes/{node_type}")
async def get_node_def(node_type: str) -> dict[str, Any]:
    """Get a single node definition."""
    node = get_node(node_type)
    if not node:
        raise HTTPException(status_code=404, detail=f"Node type '{node_type}' not found")
    return {
        "type": node.type,
        "name": node.name,
        "category": node.category,
        "description": node.description,
        "icon": node.icon,
        "color": node.color,
        "inputs": [{"id": i.id, "name": i.name, "type": i.type, "required": i.required} for i in node.inputs],
        "outputs": [{"id": o.id, "name": o.name, "type": o.type, "required": o.required} for o in node.outputs],
        "config_schema": node.config_schema,
    }


@router.post("/workflows")
async def create_workflow(body: dict[str, Any]) -> Workflow:
    wf = Workflow(
        id=body.get("id", f"wf_{uuid4().hex[:8]}"),
        name=body.get("name", "Untitled Workflow"),
        description=body.get("description", ""),
    )
    _workflows[wf.id] = wf
    return wf


@router.get("/workflows")
async def list_workflows() -> list[Workflow]:
    return list(_workflows.values())


@router.get("/workflows/{wf_id}")
async def get_workflow(wf_id: str) -> Workflow:
    if wf_id not in _workflows:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return _workflows[wf_id]


@router.put("/workflows/{wf_id}")
async def update_workflow(wf_id: str, body: dict[str, Any]) -> Workflow:
    if wf_id not in _workflows:
        raise HTTPException(status_code=404, detail="Workflow not found")
    wf = _workflows[wf_id]
    if "name" in body:
        wf.name = body["name"]
    if "description" in body:
        wf.description = body["description"]
    if "nodes" in body:
        wf.nodes = [WorkflowNode(**n) for n in body["nodes"]]
    if "edges" in body:
        wf.edges = [WorkflowEdge(**e) for e in body["edges"]]
    wf.version += 1
    return wf


@router.delete("/workflows/{wf_id}")
async def delete_workflow(wf_id: str) -> dict[str, bool]:
    if wf_id in _workflows:
        del _workflows[wf_id]
        return {"deleted": True}
    raise HTTPException(status_code=404, detail="Workflow not found")


@router.post("/workflows/{wf_id}/execute")
async def execute_workflow(wf_id: str, body: dict[str, Any] | None = None) -> WorkflowExecution:
    if wf_id not in _workflows:
        raise HTTPException(status_code=404, detail="Workflow not found")
    wf = _workflows[wf_id]
    max_steps = (body or {}).get("max_steps", 500)
    engine = ExecutionEngine(wf)
    return await engine.execute(max_steps=max_steps)


@router.post("/export")
async def export_workflow(req: ExportRequest) -> dict[str, Any]:
    if req.workflow_id not in _workflows:
        raise HTTPException(status_code=404, detail="Workflow not found")
    wf = _workflows[req.workflow_id]
    if req.format == "python":
        code = _export_to_python(wf)
        return {"format": "python", "code": code}
    if req.format == "json":
        return {"format": "json", "code": wf.model_dump_json(indent=2)}
    return {"format": req.format, "code": wf.model_dump_json()}


def _export_to_python(wf: Workflow) -> str:
    """Generate Python code from a workflow."""
    lines = [
        "# Generated by ChainForge",
        "import asyncio",
        "",
        f"async def {wf.name.lower().replace(' ', '_')}():",
        f'    """{wf.description}"""',
        "",
    ]
    for node in wf.nodes:
        cfg = node.data or {}
        if node.type.startswith("input_"):
            val = cfg.get("value", "")
            lines.append(f"    {node.id} = {val!r}")
        elif node.type.startswith("llm_"):
            lines.append(f"    {node.id} = '[{node.name}] LLM call'")
        elif node.type.startswith("tool_"):
            lines.append(f"    {node.id} = '[{node.name}] Tool call'")
        else:
            lines.append(f"    {node.id} = '[{node.name}]'")
    lines.append("")
    lines.append("    return " + (wf.nodes[-1].id if wf.nodes else "None"))
    lines.append("")
    lines.append(f"if __name__ == '__main__':")
    lines.append(f"    asyncio.run({wf.name.lower().replace(' ', '_')}())")
    return "\n".join(lines)


@router.post("/deploy")
async def deploy_workflow(req: DeployRequest) -> dict[str, Any]:
    if req.workflow_id not in _workflows:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return {
        "status": "deployed",
        "workflow_id": req.workflow_id,
        "target": req.target,
        "url": f"http://localhost:8000/workflows/{req.workflow_id}",
    }
